# docker-compose.yml
services:
 backend:
    image: videobackend:0.1
    build:
      context: ./config/django_image
    volumes:
      - ./src/django:/usr/src/app:delegated
    ports:
      - "8000:8000"
    networks:
      red:

networks:
  red:
